BANNER_NAME_EXTEND = 20  # This many space between the name and the ':'.

REDIS_HOST_ENVVAR = "CLI_REDIS_HOST_ADDRESS"
REDIS_PORT_ENVVAR = "CLI_REDIS_PORT_ADDRESS"
HTTPSERVER_HOST_ENVVAR = "CLI_HTTPSERVER_HOST_ADDRESS"
HTTPSERVER_PORT_ENVVAR = "CLI_HTTPSERVER_PORT_ADDRESS"
