on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    name: Run existing tests
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.11, 3.12, 3.13]
    steps:
      - name: Setup Python
        uses: actions/setup-python@v5.6.0
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/checkout@v4
      - name: Install sophys-common
        run: pip install git+https://github.com/cnpem/sophys-common.git
      - name: Install package
        run: pip install ".[all]"
      - name: Run pytest
        run: pytest -vvv
